- display_name: Dolci-Instruct-SFT
  description: "Dolci Instruct SFT"
  path: allenai/Dolci-Instruct-SFT
  subset: default
  split: train
  messages_field: messages
  query_filter:
    - role
    - user
  query_field: content
  index_name: null